name: Test and Merge

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Write service account key (from secret)
      env:
        SA_JSON: ${{ secrets.SA_JSON }}
      run: |
        echo "$SA_JSON" > /tmp/sa.json
        chmod 600 /tmp/sa.json

    - name: Run tests
      env:
          GAUTH_CREDENTIALS_PATH: /tmp/sa.json
          STND_DEFAULT_NUM_ATTEMTPS: 3
      run: |
        pytest tests/run_from_csv/test_main.py -v
        pytest tests/test_import_utils.py -v
        pytest tests/test_data_utils.py -v
        pytest tests/test_gspread_client.py -v
        pytest tests/test_gdrive_utils.py -v

    - name: Remove credentials
      if: always()
      run: |
        shred -u /tmp/sa.json || rm -f /tmp/sa.json

    # - name: Check test coverage
    #   run: |
    #     pip install pytest-cov
    #     pytest tests/run_from_csv/test_main.py --cov=src.stuned.run_from_csv --cov-report=xml

    # - name: Upload coverage report
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true
